#!/usr/bin/env python3

import argparse
from template import TemplateSolution
import subprocess
import sys

def main():
    parser = TemplateSolution.setup_argparse()
    parser.add_argument('-d', '--day', dest='day', type=str, required=True)  # e.g. 2021/01

    args = parser.parse_args()
    day = args.day

    argv = sys.argv[:1]
    filtered_argv = []
    skip_next = False
    for el in argv:
        if skip_next:
            skip_next = False
            continue
        if el == '-d':
            skip_next = True
            continue
        elif el.startswith('--day='):
            continue
        else:
            filtered_argv.append(el)
    print(f'calling python {day}/solution.py')
    subprocess.call(['python', f'{day}/solution.py'] + filtered_argv, cwd=day)


if __name__ == '__main__':
    main()