#!/usr/bin/env python3

import argparse

from path import Path
from template import TemplateSolution
import subprocess
import sys
from template import get_solution_instance
import importlib

def main():
    parser = TemplateSolution.setup_argparse()

    args = parser.parse_args()

    # dynamically import the solution file
    solution_folder = Path(__file__).parent / f'{args.year}' / f'day{args.day:02}'
    sys.path.append(str(solution_folder))
    for file in solution_folder.files('*.py'):
        module_name = file.name.replace('.py', '')
        importlib.import_module(module_name)

    # run the solution
    get_solution_instance(args.year, args.day).main()

if __name__ == '__main__':
    main()